# Generated by Django 4.2.20 on 2025-03-26 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="category",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
    ]
